repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=3000']
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    # disabled to protect R generated files
    # -   id: end-of-file-fixer
    # -   id: trailing-whitespace

# disabled to protect R generated markdown files
# -   repo: https://github.com/executablebooks/mdformat
#     rev: 0.7.6
#     hooks:
#     -   id: mdformat
-   repo: https://github.com/hadolint/hadolint
    rev: v2.4.1
    hooks:
    - id: hadolint-docker
# R specific
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    - id: readme-rmd-rendered
