version: 2.1

jobs:
  build_dev_docker:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Building CI image
          command: |
            set -e
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
            mkdir -p workspace
            docker save -o workspace/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_SHA1}.tar $CIRCLE_SHA1
      - persist_to_workspace:
          root: workspace
          paths:
            - $CIRCLE_SHA1.tar
  build_binary:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Building R binary
          command: |
            docker load -i /tmp/workspace/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_SHA1}.tar
            docker run -ti --rm ${CIRCLE_PROJECT_REPONAME}_${CIRCLE_SHA1} r -e "devtools::build(binary = TRUE)"


workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - build_dev_docker:
          context:
            - dockerhub-casmservice
          filters:
            tags:
              only: /.+/
      - build_binary:
          requires:
            - build_dev_docker
          filters:
            tags:
              only: /.+/
