version: 2.1

jobs:
  license_chk:
    machine:
      # need machine as want to mount a volume
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Execute skywalking-eyes check of licenses
          # once 0.2.0 released change image
          command: |
            set -e
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker run --rm -v $(pwd):/github/workspace ghcr.io/apache/skywalking-eyes/license-eye@sha256:17a4e86591c9908c8e76531943d5522881a82a33580ad7bdf36938517ef25aa9 header check
  build_docker:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Building CI image
          command: |
            set -e
            LC_REPO=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]')
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build -f Dockerfile -t $LC_REPO:$CIRCLE_SHA1 .
            mkdir -p workspace
            docker save -o workspace/dev-image.tar ${LC_REPO}:$CIRCLE_SHA1
      - persist_to_workspace:
          root: workspace
          paths:
            - dev-image.tar
  unittests:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Devtools unittests
          command: |
            set -e
            LC_REPO=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]')
            docker load -i /tmp/workspace/dev-image.tar
            docker run -u root -w /build -ti --rm ${LC_REPO}:${CIRCLE_SHA1} r -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'
  devtools_checks:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Devtools checks
          command: |
            set -e
            LC_REPO=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]')
            docker load -i /tmp/workspace/dev-image.tar
            container_id=$(docker run -u root -w /build -d --rm ${LC_REPO}:${CIRCLE_SHA1} sleep 10000)
            set +e
            mkdir ~/check_out
            #docker exec ${container_id} r -e 'devtools::check(document = FALSE, quiet = TRUE, args = c("--no-tests", check_dir = "~/check_out"), error_on = c("never"))'
            docker exec ${container_id} r -e 'devtools::check(document = FALSE, args =c("--no-tests"), check_dir = "~/check_out", error_on = c("never"));'
            #docker exec ${container_id} grep -qvP '^Status:.*ERROR' /tmp/rcrispr.Rcheck/00check.log; res=$?
            echo "LS ~/check_out"
            ls -l ~/check_out
            echo "LS TMP *"
            ls -l /tmp/
            #docker exec ${container_id} cat /tmp/rcrispr.Rcheck/00check.log
            docker rm -f $container_id
            if [ "$res" -ne "0" ]; then
              exit 1
            fi
            exit 0

  deploy:
    machine:
      image: ubuntu-2004:202107-02
    environment:
      IMAGE_NAME: quay.io/wtsicgp/rcrispr
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build R binary, push docker-image
          command: |
            set -e
            mkdir -p /tmp/build
            LC_REPO=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]')
            docker load -i /tmp/workspace/dev-image.tar
            container_id=$(docker run -u root -w /build -d --rm ${LC_REPO}:${CIRCLE_SHA1} sleep 1000)
            set +e
            docker exec $container_id r -e "devtools::build(binary = TRUE, path = './')" ; res=$?
            docker exec $container_id bash -c 'mkdir -p dist && mv rcrispr*.tar.gz dist/.'
            docker cp $container_id:/build/dist /tmp/build
            docker rm -f $container_id
            if [ "$res" -ne "0" ]; then
              exit $res
            fi
            set -e
            BRANCH_OR_TAG="${CIRCLE_TAG:-$CIRCLE_BRANCH}"
            CLEAN_BRANCH=$(echo $BRANCH_OR_TAG | tr / -)
            if [ "$CIRCLE_TAG" = "$BRANCH_OR_TAG" ]; then
              docker tag ${LC_REPO}:${CIRCLE_SHA1} $IMAGE_NAME:$CLEAN_BRANCH
              echo "$QUAYIO_PASSWORD" | docker login -u "$QUAYIO_USER" --password-stdin quay.io
              echo 'Pushing image'
              docker push $IMAGE_NAME:$CLEAN_BRANCH
            else
              echo "I am not a tag so not pushing image"
            fi
      # to publish R tar to github automatically: https://circleci.com/blog/publishing-to-github-releases-via-circleci/
      - store_artifacts:
          path: /tmp/build
          #path: /tmp/build/rcrispr_R_x86_64-pc-linux-gnu.tar.gz
          #destination: rcrispr_R_x86_64-pc-linux-gnu.tar.gz



workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - license_chk:
          context:
            - dockerhub-casmservice
      - build_docker:
          context:
            - dockerhub-casmservice
          filters:
            tags:
              only: /.+/
      - unittests:
          requires:
            - build_docker
          filters:
            tags:
              only: /.+/
      - devtools_checks:
          requires:
            - build_docker
          filters:
            tags:
              only: /.+/
      - deploy:
          requires:
            - license_chk
            - build_docker
            - unittests
            - devtools_checks
          context:
            - quayio-casmservice
          filters:
            tags:
              only: /.+/
