version: 2.1

jobs:
  build_dev_docker:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Building CI image
          command: |
            set -e
            LC_REPO=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]')
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            echo "docker build -f Dockerfile-ci -t $LC_REPO:$CIRCLE_SHA1 ."
            docker pull alpine:latest
            docker tag alpine:latest ${LC_REPO}:$CIRCLE_SHA1
            mkdir -p workspace
            docker save -o workspace/dev-image.tar ${LC_REPO}:$CIRCLE_SHA1
      - persist_to_workspace:
          root: workspace
          paths:
            - dev-image.tar
  build_binary:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Building R binary
          command: |
            LC_REPO=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]')
            docker load -i /tmp/workspace/dev-image.tar
            docker run -ti --rm ${LC_REPO}_${CIRCLE_SHA1} r -e "devtools::build(binary = TRUE)"
          # this will need to be done via a timed run, and then copy the generated file out


workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - build_dev_docker:
          context:
            - dockerhub-casmservice
          filters:
            tags:
              only: /.+/
      - build_binary:
          requires:
            - build_dev_docker
          filters:
            tags:
              only: /.+/
