utils::globalVariables(c("sgRNA", "gene", "Gene", 'sgrna',
                         "filename", "label", "id_col", "gene_col",
                         "sgrna_lfc", "spread", "gather", "lfc",
                         "plasmid","control","treatment",
                         "group","reads","chr",
                         "slot<-", ".",
                         "data", "end", "filter_mean", "filter_median", "start",
                         "neg.fdr", 'neg.goodsgrna', 'neg.lfc',
                         "pos.fdr", 'pos.goodsgrna', 'pos.lfc',
                         "LFC", "FDR", "is_enriched", "is_depleted",
                         "prop_mapped_reads", "pct_low_sgrnas", "pct_zero_sgrnas",
                         "low_counts_per_sample", ":=", "total_reads", "total_counts",
                         "pct_mapped_reads", "unmapped", "pct_unmapped_reads",
                         "category", "num_reads", "df", "data"))
